### ISSUE TITLE
Newer button doesn't seem to work on page 2:)

### ISSUE THREAD

**Issue by BDHU** [mlampros/mlampros.github.io#1]
The Newer button at the bottom of page 2 doesn't seem to lead you back to the previous page:)

**Comment by mlampros** [comment]
@BDHU,

I'm sorry for the late reply. Which newer button do you mean? Can you attach the url of the web page.

**Comment by BDHU** [comment]
The page link is [here](http://mlampros.github.io/page2/). When you scroll down to the bottom of the page you can see the Older and Newer button to reach old and new posts. However the Newer button doesn't have any effect as clicking it will still remain on http://mlampros.github.io/page2/. I have this exact same issue and it appears something is wrong with `index.html`:)

**Comment by mlampros** [comment]
Thanks for making me aware of this. Moreover, when I click more than once the *older* button it gives '404: Page not found' although there are still older blogs in the *archives* section. You also have a blog based on the [lanyon theme](https://github.com/BDHU/lanyonm.github.io). I have to search on the web for this one. If you find a solution to the issue I'll be glad if you post it here too. At least someone (currently) has the option to navigate through the *archives* section based on the dates.

**Comment by mlampros** [comment]
@BDHU,

I found the issue and thanks for the hint to look at the index.html page. I had to look to the initial blog that I wrote back [in 2016](http://mlampros.github.io/2016/01/31/first-blog-post/) and especially the following two links helped to resolve this one [here](http://anandmanisankar.com/) and [here](https://github.com/msanand/msanand.github.io/blob/master/index.html) (it was one of the blogs that I used to set up mine). I replaced the following script in the index.html page,

```R

<div class="pagination">
  {% if paginator.next_page %}
    <a class="pagination-item older" href="{{ site.baseurl }}page{{paginator.next_page}}">Older</a>
  {% else %}
    <span class="pagination-item older">Older</span>
  {% endif %}
  {% if paginator.previous_page %}
    {% if paginator.page == 2 %}
      <a class="pagination-item newer" href="{{ site.baseurl }}">Newer</a>
    {% else %}
      <a class="pagination-item newer" href="{{ site.baseurl }}page{{paginator.previous_page}}">Newer</a>
    {% endif %}
  {% else %}
    <span class="pagination-item newer">Newer</span>
  {% endif %}
</div>

```

with this one,

```R

<div class="pagination">
  {% if paginator.next_page %}
    <a class="pagination-item older" href="{{ "/" | relative_url }}page{{paginator.next_page}}">Older</a>
  {% else %}
    <span class="pagination-item older">Older</span>
  {% endif %}
  {% if paginator.previous_page %}
    {% if paginator.page == 2 %}
      <a class="pagination-item newer" href="{{ "/" | relative_url }}">Newer</a>
    {% else %}
      <a class="pagination-item newer" href="{{ "/" | relative_url }}page{{paginator.previous_page}}">Newer</a>
    {% endif %}
  {% else %}
    <span class="pagination-item newer">Newer</span>
  {% endif %}
</div>

```

and know it works as expected. Thanks again for making me aware of this issue.

**Comment by BDHU** [comment]
That solves my problem. I also find official [documentation](https://jekyllrb.com/docs/pagination/) regarding pagination in Jekyll if the problem appears later.

**Comment by mlampros** [comment]
thanks for the documentation web-link. I close the issue for now, feel free to reopen it.
