### ISSUE TITLE
Your CV link doesn't load

### ISSUE THREAD

**Issue by cmcaine** [mlampros/mlampros.github.io#2]
Link on your site redirects to github which (at least on this machine) fails to preview the file.

I was just poking around, afraid I'm not an exciting recruiter here to offer you $DREAM_JOB ;)

**Comment by mlampros** [comment]
Hi @cmcaine,

thanks for making me aware of this issue. I really don't know if it has to do with the version of your browser, the type of your browser or if you don't have the pdf viewer / plugin installed. For me works fine both on Google Chrome and Firefox.
To continue from your last sentence "an exciting recruiter that would offer me a $DREAM_JOB" can download the .pdf file directly from my github account using the [download](https://github.com/mlampros/mlampros.github.io/blob/master/Curriculum_Vitae_Github.pdf) button.
have a nice day.

**Comment by cmcaine** [comment]
It's displaying it fine today for me as well. Sorry to open a spurious issue, I'll put this down to general non-determinism ;)
